name: Linking and and formatting on PR

on:
  pull_request:
    branches:
      - "**"

jobs:
  continuous-integration:
    name: Perform  linking, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Dependecies
        run: npm install --legacy-peer-deps

      - name: Run linting check
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:fix
